name: Release stable

env:
  GORELEASER_GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  FURY_PUSH_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
  FURY_USERNAME: ${{ secrets.FURY_USERNAME }}

on:
  repository_dispatch:
    types: [release_stable]

jobs:
  release_stable:
    name: Release stable version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          load-mode: strict

      - name: Set up Go ${{ vars.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Create stable release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.client_payload.tag_name }}
          name: ${{ github.event.client_payload.tag_name }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: ~> v2
          args: release --clean
